### PR TITLE
Made a union out of jointmode and allowMidside for backwards compatib…

### PR DESCRIPTION
**Pull request by enzo1982**
…ility.

Fixes issue #9.

### CODE REVIEW

**Comment by ilovezfs** [comment]
do you know if this is clang compatible?

**Comment by ilovezfs** [comment]
looks like it is :)

**Comment by knik0** [comment]
@ilovezfs @enzo1982  Oops, I already pushed my own fix.

**Comment by enzo1982** [comment]
@knik0: No worries. I was too slow. ;)

**Comment by ilovezfs** [comment]
@knik0 do you mind cutting a new release? That should stop the bleeding in terms of downstreams running around worrying about this :)

**Comment by knik0** [comment]
@ilovezfs released 1.29.9.2

**Comment by ilovezfs** [comment]
@knik0 sweet. I'll close https://github.com/Homebrew/homebrew-core/pull/20625 and open a PR for that.

**Pull request closed without merging**
